<?xml version="1.0"?>
<package format="3">
  <name>projectairsim_rosbridge</name>
  <version>{# include "client_version.txt" #}</version>
  <description>ROS-version-neutral Project AirSim bridge implementation.</description>
  <maintainer email="opensource@iamaisim.com">IAMAI Simulations</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>radar_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>sensor_msgs_py</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <test_depend>ament_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
